server:
  port: 8882

spring:
  application:
    name: rabbitmq-receiver
  rabbitmq:
    host: 127.0.0.1
    password: admin
    port: 5672
    username: admin
    virtual-host: /
    #指定client连接到的server的地址，多个以逗号分隔(优先取addresses，然后再取host)
    addresses: 127.0.0.1:5672
    requested-heartbeat: 30
    #connection-timeout:
    cache:
      channel:
        #缓存中保持的channel数量
        size: 1
        #缓存数量被设置时，从缓存中获取一个channel的超时时间，单位毫秒；如果为0，则总是创建一个新channel
        checkout-timeout: 5
      connection:
        #缓存的连接数，只有是CONNECTION模式时生效
        mode: connection
        size: 10
    listener:
      simple:
        prefetch: 1


# listener
#spring.rabbitmq.listener.simple.auto-startup: 是否启动时自动启动容器
#spring.rabbitmq.listener.simple.acknowledge-mode: 表示消息确认方式，其有三种配置方式，分别是none、manual和auto；默认auto
#spring.rabbitmq.listener.simple.concurrency: 最小的消费者数量
#spring.rabbitmq.listener.simple.max-concurrency: 最大的消费者数量
#spring.rabbitmq.listener.simple.prefetch: 指定一个请求能处理多少个消息，如果有事务的话，必须大于等于transaction数量.
#spring.rabbitmq.listener.simple.transaction-size: 指定一个事务处理的消息数量，最好是小于等于prefetch的数量.
#spring.rabbitmq.listener.simple.default-requeue-rejected: 决定被拒绝的消息是否重新入队；默认是true（与参数acknowledge-mode有关系）
#spring.rabbitmq.listener.simple.idle-event-interval: 多少长时间发布空闲容器时间，单位毫秒
#
#spring.rabbitmq.listener.simple.retry.enabled: 监听重试是否可用
#spring.rabbitmq.listener.simple.retry.max-attempts: 最大重试次数
#spring.rabbitmq.listener.simple.retry.initial-interval: 第一次和第二次尝试发布或传递消息之间的间隔
#spring.rabbitmq.listener.simple.retry.multiplier: 应用于上一重试间隔的乘数
#spring.rabbitmq.listener.simple.retry.max-interval: 最大重试时间间隔
#spring.rabbitmq.listener.simple.retry.stateless: 重试是有状态or无状态
#
#
## template
#spring.rabbitmq.template.mandatory: 启用强制信息；默认false
#spring.rabbitmq.template.receive-timeout: receive() 操作的超时时间
#spring.rabbitmq.template.reply-timeout: sendAndReceive() 操作的超时时间
#spring.rabbitmq.template.retry.enabled: 发送重试是否可用
#spring.rabbitmq.template.retry.max-attempts: 最大重试次数
#spring.rabbitmq.template.retry.initial-interval: 第一次和第二次尝试发布或传递消息之间的间隔
#spring.rabbitmq.template.retry.multiplier: 应用于上一重试间隔的乘数
#spring.rabbitmq.template.retry.max-interval: 最大重试时间间隔
#


logging:
  level:
    org: INFO

receiver:
  queue1:
    wait: 5000
  queue2:
    wait: 5000