server:
  port: 8882

spring:
  application:
    name: rabbitmq-receiver
  rabbitmq:
    host: 127.0.0.1
    password: admin
    port: 5672
    username: admin
    listener:
      prefetch: 1

logging:
  level:
    org: INFO

receiver:
  queue1:
    wait: 5000
  queue2:
    wait: 5000